[CmdletBinding(SupportsShouldProcess=$true)]
param([Parameter(Mandatory=$true)][string]$Receipt,[string]$CodexHome=$(if($env:CODEX_HOME){$env:CODEX_HOME}else{Join-Path $env:USERPROFILE '.codex'}))
$ErrorActionPreference='Stop';$CodexRoot=[IO.Path]::GetFullPath($CodexHome);$ReceiptRoot=Join-Path $CodexRoot 'receipts'
function Get-Hash([string]$p){
  $stream=$null;$sha256=$null
  try{
    $stream=[IO.File]::Open($p,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read)
    $sha256=[Security.Cryptography.SHA256]::Create()
    (([BitConverter]::ToString($sha256.ComputeHash($stream))) -replace '-','').ToLowerInvariant()
  } finally {
    if($sha256){$sha256.Dispose()}
    if($stream){$stream.Dispose()}
  }
}
function Copy-FileDurable([string]$Source,[string]$Destination){$directory=Split-Path -Parent $Destination;New-Item -ItemType Directory -Force -Path $directory|Out-Null;$temporary=Join-Path $directory ".codexpro-$([guid]::NewGuid().ToString('N')).tmp";$input=$null;$output=$null;try{$input=[IO.File]::Open($Source,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$output=[IO.File]::Open($temporary,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$input.CopyTo($output);$output.Flush($true);$output.Dispose();$output=$null;$input.Dispose();$input=$null;if(Test-Path -LiteralPath $Destination){$replaceBackup=Join-Path $directory ".codexpro-$([guid]::NewGuid().ToString('N')).bak";try{[IO.File]::Replace($temporary,$Destination,$replaceBackup,$true)}finally{if(Test-Path -LiteralPath $replaceBackup){Remove-Item -LiteralPath $replaceBackup -Force}}}else{[IO.File]::Move($temporary,$Destination)}}finally{if($output){$output.Dispose()};if($input){$input.Dispose()};if(Test-Path -LiteralPath $temporary){Remove-Item -LiteralPath $temporary -Force}}}
function Test-IsWithinRoot([string]$r,[string]$p){$r=[IO.Path]::GetFullPath($r).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);$p=[IO.Path]::GetFullPath($p);$p.StartsWith($r+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)}
function Get-SafeChild([string]$r,[string]$x){if([string]::IsNullOrWhiteSpace($x)-or[IO.Path]::IsPathRooted($x)-or$x -match '(^|[\\/])\.{1,2}([\\/]|$)'){throw "unsafe relative path: $x"};$p=[IO.Path]::GetFullPath((Join-Path $r $x));if(!(Test-IsWithinRoot $r $p)){throw "path escapes root: $x"};$cursor=Split-Path -Parent $p;while((Test-IsWithinRoot $r $cursor) -and $cursor -ne [IO.Path]::GetFullPath($r)){if(Test-Path -LiteralPath $cursor){$i=Get-Item -LiteralPath $cursor -Force;if($i.LinkType){throw "symlink/reparse path refused: $cursor"}};$cursor=Split-Path -Parent $cursor};$p}
$fullReceipt=[IO.Path]::GetFullPath($Receipt);if(!(Test-IsWithinRoot $ReceiptRoot $fullReceipt) -or !(Test-Path -LiteralPath $fullReceipt) -or (Get-Item -LiteralPath $fullReceipt -Force).LinkType){throw 'receipt must be owned by this CODEX_HOME'}
$value=Get-Content -LiteralPath $fullReceipt -Raw|ConvertFrom-Json;if($value.schema -notin @('codexpro.install-receipt/v2','codexpro.install-receipt/v3','codexpro.install-receipt/v4')){throw 'unsupported receipt schema'};if($value.files -isnot [System.Array] -or !(Test-IsWithinRoot (Join-Path $CodexRoot 'backups') $value.backup)){throw 'receipt backup must be owned by this CODEX_HOME'}
if($value.schema -in @('codexpro.install-receipt/v3','codexpro.install-receipt/v4')){$walPath=[string]$value.wal;if(!(Test-IsWithinRoot $value.backup $walPath) -or !(Test-Path -LiteralPath $walPath -PathType Leaf) -or (Get-Item -LiteralPath $walPath -Force).LinkType){throw 'receipt WAL binding invalid'};$wal=Get-Content -LiteralPath $walPath -Raw|ConvertFrom-Json;$expectedWal=if($value.schema -eq 'codexpro.install-receipt/v4'){'codexpro.install-wal/v3'}else{'codexpro.install-wal/v2'};if($wal.schema -ne $expectedWal -or $wal.status -ne 'COMPLETE' -or [string]$wal.transaction_id -ne [string]$value.transaction_id -or [string]$wal.receipt -ne $fullReceipt){throw 'receipt/WAL transaction binding mismatch'}}
if($value.schema -eq 'codexpro.install-receipt/v3' -and $value.dependency.mode -eq 'applied'){[ordered]@{schema='codexpro.rollback-result/v1';receipt=$fullReceipt;status='CONFLICT';conflicts=@(@{path='dependency';action='external_legacy_dependency_requires_separate_approval'})}|ConvertTo-Json -Depth 5;exit 2}
$conflicts=@();$plans=@();foreach($record in $value.files){$relative=[string]$record.path;$destination=Get-SafeChild $CodexRoot $relative;$exists=Test-Path -LiteralPath $destination;if($exists -and (Get-Item -LiteralPath $destination -Force).LinkType){$conflicts+=@{path=$relative;action='destination_symlink'};continue};$hash=if($exists){Get-Hash $destination}else{$null};if($record.action -eq 'created'){if(!$exists){continue};if($hash -eq [string]$record.installed_sha256){$plans+=@{operation='remove';destination=$destination;record=$record}}else{$conflicts+=@{path=$relative;action='preserved_modified_created'}};continue};if($record.action -eq 'overwritten'){$backup=Get-SafeChild $value.backup $relative;if(!(Test-Path -LiteralPath $backup -PathType Leaf) -or (Get-Item -LiteralPath $backup -Force).LinkType -or (Get-Hash $backup)-ne [string]$record.backup_sha256){$conflicts+=@{path=$relative;action='backup_invalid'};continue};if($exists -and $hash -eq [string]$record.installed_sha256){$plans+=@{operation='restore';destination=$destination;backup=$backup;record=$record}}elseif(!($exists -and $hash -eq [string]$record.backup_sha256)){$conflicts+=@{path=$relative;action='preserved_modified_overwritten'}};continue};if($record.action -eq 'removed'){if($value.schema -ne 'codexpro.install-receipt/v4' -or [string]$record.transaction_id -ne [string]$value.transaction_id -or [string]$record.rollback_binding -ne [string]$value.transaction_id -or $record.expected_absence -ne $true){$conflicts+=@{path=$relative;action='removed_binding_invalid'};continue};$backup=Get-SafeChild $value.backup $relative;if([string]$record.backup -ne $backup -or !(Test-Path -LiteralPath $backup -PathType Leaf) -or (Get-Item -LiteralPath $backup -Force).LinkType -or (Get-Hash $backup)-ne [string]$record.backup_sha256){$conflicts+=@{path=$relative;action='removed_backup_invalid'};continue};if($exists){if($hash -ne [string]$record.expected_sha256){$conflicts+=@{path=$relative;action='destination_recreated_removed'}}}else{$plans+=@{operation='restore';destination=$destination;backup=$backup;record=$record}};continue};$conflicts+=@{path=$relative;action='invalid_receipt_action'}}
if($conflicts.Count){[ordered]@{schema='codexpro.rollback-result/v1';receipt=$fullReceipt;status='CONFLICT';conflicts=$conflicts}|ConvertTo-Json -Depth 5;exit 2}
foreach($plan in $plans){try{if($plan.operation -eq 'remove'){if($PSCmdlet.ShouldProcess($plan.destination,'remove unchanged receipt-created file')){Remove-Item -LiteralPath $plan.destination -Force}}elseif($PSCmdlet.ShouldProcess($plan.destination,'restore exact durable backup')){Copy-FileDurable $plan.backup $plan.destination}}catch{$conflicts+=@{path=$plan.record.path;action='rollback_error';detail=$_.Exception.Message};break}}
$status=if($conflicts.Count){'CONFLICT'}else{'COMPLETE'};$result=[ordered]@{schema='codexpro.rollback-result/v1';receipt=$fullReceipt;status=$status;conflicts=$conflicts};$result|ConvertTo-Json -Depth 5
if($conflicts.Count){exit 2}
